### ISSUE TITLE
Admin cannot modify users

### ISSUE THREAD

**Issue by VictoriaVasys** [bschwartz10/little_shop_of_orders#52]
As a logged in Admin
      I can modify my account data
      But I cannot modify any other user's account data

**Comment by bschwartz10** [comment]
add edit user page

**Comment by VictoriaVasys** [comment]
Nice work!

**Comment by VictoriaVasys** [comment]
Nice work!

On Apr 15, 2017 9:33 PM, "Brett Schwartz" <notifications@github.com> wrote:

Closed #52 <https://github.com/bschwartz10/little_shop_of_orders/issues/52>.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/bschwartz10/little_shop_of_orders/issues/52#event-1044264917>,
or mute the thread
